# local use only; server deployment uses a docker-compose file that is not in git
# you will find that file in /home/docker/${project}/...

version: '3.1'
services:
  netcoreapp1:
    image: netcoreapp-api-image
    build: .
    container_name: itec-mobile-api-1
    restart: always
    environment:
      - NETCORE_USER_UID=69
      - TZ=Europe/Bucharest
      - ASPNETCORE_URLS=http://+:5030
    env_file:
      - ./conf.vars.local
    ports:
      - 5010:5030
    networks:
      mariadb-net:
        aliases:
          - mobile-api-1
            

networks:
  mariadb-net:
    external:
      name: db-net